export const theme = {
  colors: {
    bg: {
      base: '#fafaf8',
      elevated: '#ffffff',
      subtle: '#f3f2f0',
      dark: '#0a1816',
      darker: '#050d0c',
    },
    text: {
      primary: '#0a0a0a',
      secondary: '#555555',
      muted: '#999999',
      placeholder: '#cccccc',
      onDark: '#fafaf8',
      onDarkMuted: '#7d8b89',
    },
    border: {
      default: '#e8e8e2',
      strong: '#0a0a0a',
      onDark: '#1f2d2b',
    },
    accent: {
      moon: '#efc94c',
      moonSoft: '#f5d76e',
      glow: 'rgba(245, 215, 110, 0.14)',
    },
  },
  typography: {
    fontDisplay: "'Noto Serif Display', 'Zen Kaku Gothic New', serif",
    fontDisplaySans: "'Plus Jakarta Sans', 'Zen Kaku Gothic New', system-ui, sans-serif",
    fontSerif: "'Noto Serif Display', 'Zen Kaku Gothic New', serif",
    fontSans: "'Plus Jakarta Sans', 'Zen Kaku Gothic New', 'Helvetica Neue', sans-serif",
    fontJP: "'Zen Kaku Gothic New', sans-serif",
    fontMono: "'JetBrains Mono', 'IBM Plex Mono', ui-monospace, monospace",
    size: {
      xs: '11px',
      sm: '13px',
      base: '14px',
      md: '16px',
      lg: '18px',
      xl: '22px',
      '2xl': '28px',
      '3xl': '40px',
      '4xl': '56px',
      '5xl': '80px',
    },
    weight: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    lineHeight: {
      tight: 1.1,
      snug: 1.3,
      normal: 1.6,
      loose: 1.85,
    },
    letterSpacing: {
      tighter: '-1px',
      tight: '-0.5px',
      normal: '0',
      wide: '2px',
      wider: '3px',
      widest: '4px',
    },
  },
  spacing: {
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    '32': '128px',
  },
  radius: {
    sm: '3px',
    md: '6px',
    lg: '10px',
    full: '9999px',
  },
  breakpoints: {
    sm: '600px',
    md: '900px',
    lg: '1200px',
  },
  layout: {
    maxWidth: '1180px',
    navHeight: '64px',
  },
  motion: {
    fast: '180ms',
    base: '320ms',
    slow: '600ms',
    ease: 'cubic-bezier(0.22, 1, 0.36, 1)',
  },
} as const;

export type Theme = typeof theme;
